### ISSUE TITLE
Shell Configuration Home

### ISSUE THREAD

**Issue by stepenik** [Keidan/SshServer#1]
In ShellConfiguration you are put "DEFAULT_HOME", but when you make connection with SSH your root folder is not "/storage/emulated/0/download". Your root folder is "/".

`public static final String DEFAULT_HOME = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).getParentFile().getAbsolutePath();`

[Code](https://github.com/Keidan/SshServer/blob/d8b4c9194c9c35dd4483375ea7aa35f29fe9562b/app/src/main/java/fr/ralala/sshd/net/SshServer.java#L78)

**Comment by Keidan** [comment]
Hello,

With this [commit](https://github.com/Keidan/SshServer/commit/c364062f7ae56c974ae6e5d0630751657466d8b0) the shell will automatically be started in the directory specified by the variable HOME.

**Comment by stepenik** [comment]
Nice @Keidan this bug is fixed now.
