### ISSUE TITLE
Run app on port 22

### ISSUE THREAD

**Issue by stepenik** [Keidan/SshServer#3]
I tried run app on port 22 official port for SSH but in Toast I see exception is it not possible to run on this port. I know ports under 1024 is reserved by Android OS. But in emulator GenyMotion you are root user. Do you have idea how to run on port 22 this app ?

**Comment by Keidan** [comment]
Apart from the fact that on Linux systems (+Android) it is not possible to open ports below 1024 without root privileges.

From what I see after a search on the internet, Genymotion already seems to use port 22 for its own SSH server (e. g. with this [link](https://www.genymotion.com/help/cloud-paas/faq/), and in the chapter "How do I gain access to my VD via ssh?").

If you really want to use port 22, you must find a solution to remap port 22 of Gennymotion to another port of your choice.

**Comment by stepenik** [comment]
Something like this ? But this not worked.
`Runtime.getRuntime().exec("su -c iptables -t nat -A PREROUTING -p tcp --dport 22 -j REDIRECT --to-port 7777");`

Do you have any other idea ? 👍 
Ok if Genymotion use this 3 port
– ssh IN TCP 22
– http IN TCP 80
– https IN TCP 443

But if you put for example port 23 it is same as port 22.

**Comment by Keidan** [comment]
No, your iptable command only redirects traffic from port 22 to port 7777, and this without ever changing the binded port, which will remain on port 22.

For me, the only solutions are:
- Change the default port used by the SSH server (at the configuration or startup level).
- Kill the process hoping it is not started in Respawn mode.

Before attempting other ports, make sure that they are not used by another application (see netstat), or that the OS used by your VD actually allows a non-system APK to use a port less than 1024.

**Comment by stepenik** [comment]
For this option 
> make sure that they are not used by another application (see netstat)

This port is reserved and If you not used this port in process you will not see this port. This port will turn on when system app will use. 

I tried this with https://play.google.com/store/apps/details?id=com.eolwral.osmonitor

Similar what I see from apache is FTPServer here is instruction 
https://mina.apache.org/ftpserver-project/ftpserver_port_21.html
