### ISSUE TITLE
Support of Android 7.0

### ISSUE THREAD

**Issue by Keidan** [Keidan/SshServer#4]
Due to issue #2

Added support for Android 7.x :
- [x] Downgrade of the Appache MINA library.
- [x] Changed the management of notifications that do not work on Android 8.x as on Android 7.x 
- [x] Other?

:warning: I'm not planning this evolution, it will be done when I have a moment.

**Comment by stepenik** [comment]
Ok thanks. I will test this part after you push on git.

**Comment by Keidan** [comment]
Version 1.7 of the Apache Mina library does not solve the problem.
Versions 1.6, 1.4, 1.3 bring other errors of the same type.
The versions below will force me to review the structure of the code and will probably bring their share of problems.

Unfortunately, I think that if I don't find a viable solution, this application will stay on Android 8.x+.

**Comment by stepenik** [comment]
Yes I think if you can't make to work with 1.7 version will be really hard to make with lowest versions to work. I think the best version is 0.14.0 but for this version you will need a lot of changes.

**Comment by Keidan** [comment]
As I don't want to touch the master branch to support previous versions of Android (< 8), I created a new branch (Android_7.0).

I tested these branches with the emulator proposed by AndroidStudio (API 24 and 25, so Android 7.0 and 7.1)

**Comment by Keidan** [comment]
Closed due to inactivity
